// const frontend = require('./frontend');

let sampleCarts = [
  {
    title: "Striped Flutter Sleeve Overlap Collar Peplum Hem Jacket",
    description:"Chic and feminine, this blouse features flutter sleeves, an overlap collar, and a peplum hem with striped detailing.",
    image: "../images/product_1.png",
    price: 500.0,
    category: "women",
  },
  {
    title: "Relaxed Comfort Teal Oversized T-shirt",
    description: "Effortlessly stylish and ultra-comfortable, this oversized teal t-shirt is perfect for casual days or lounging at home.",
    image: "../frontend/product_2.png",
    price: 385.0,
    category: "women",
  },
  {
    title: "Blushing Pink Draped Neckline Flowy Top",
    description: "Elevate your wardrobe with this charming pink top featuring a flattering draped neckline and a flowy silhouette for a touch of effortless elegance.",
    image:  "../frontend/product_3.png",
    price: 660.0,
    category: "women",
  },
  {
    title: "Essential Black Jacket",
    description: "Timeless style, versatile wear.",
    image:  "../frontend/product_4.png",
    price: 1350.0,
    category: "women",
  },
  {
    title: "Bold Red Oversized Tee",
    description: "Effortlessly cool, statement piece.",
    image:  "../frontend/product_5.png",
    price: 485.0,
    category: "women",
  },
  {
    title: "Mustard Dream Full Sleeve Top",
    description: "Wrap yourself in warmth and style with this chic mustard top, boasting full sleeves for cozy elegance.",
    image:  "../frontend/product_6.png",
    price: 499.0,
    category: "women",
  },
  {
    title: "Navy Blue Coat",
    description: "Timeless sophistication in navy.",
    image:  "../frontend/product_7.png",
    price: 1285.0,
    category: "women",
  },
  {
    title:"White Women's Cardigan",
    description: "Versatile elegance for any occasion.",
    image:  "../frontend/product_8.png",
    price: 1800.0,
    category: "women",
  },
  {
    title: "Light brown sweatshirt",
    description: "Cozy essential for everyday comfort.",
    image:  "../frontend/product_9.png",
    price: 600.0,
    category: "women",
  },
  {
    title: "pink sweatshirt",
    description: "casual comfort in chic pink.",
    image:  "../frontend/product_10.png",
    price: 485.0,
    category: "women",
  },
  {
    title: "men's grey red hoodie,",
    description: "Bold and vibrant, this grey&red hoodie adds a pop of attitude to your look.",
    image:  "../frontend/product_14.png",
    price: 985.0,
    category: "men",
  },
  {
    title: "green coat men,", 
    description: "classic and versatile, perfect for any occasion.",
    image:  "../frontend/product_15.png",
    price: 1585.0,
    category: "men",
  },
  {
    title: "men yellow tshirt,",
    description: "casual comfort in vibrant yellow, ideal for everyday wear.",
    image:  "../frontend/product_16.png",
    price: 285.0,
    category: "men",
  },
  {
    title: "navy blue coat for men,",
     description: "timeless sophistication, perfect for chilly days.",
    image:  "../frontend/product_17.png",
    price: 1300.0,
    category: "men",
  },
  {
    title: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
     description: "casual and comfortable",
    image:  "../frontend/product_18.png",
    price: 1550.0,
    category: "men",
  },
  {
    title: "grey men coat,",
    description: "classic and versatile, a wardrobe essential.",
    image:  "../frontend/product_19.png",
    price: 1400.0,
    category: "men",
  },
  {
    title: "Men's Stylish Blue Shirt", 
    description: "effortlessly chic and versatile, perfect for any occasion.",
    image:  "../frontend/product_20.png",
    price: 85.0,
    category: "men",
  },
  {
    title: "Nike Men's White Hoodie",
    description: "Classic comfort, signature style.",

    image:  "../frontend/product_22.png",
    price: 85.0,
    category: "men",
  },
  {
    title: "casual blue t-shirt,",
    description: "comfortable and versatile.",
    image:  "../frontend/product_23.png",
    price: 85.0,
    category: "men",
  },
  {
    title: "Zara light black leather jacket,",
    description: "Timeless style, effortless cool.",
    image:  "../frontend/product_24.png",
    price: 1200.0,
    category: "men",
  },
  {
    title: "Boys Orange Colourblocked Hooded Sweatshirt",
    description:"comfortable and classy",
    image:  "../frontend/product_26.png",
    price: 599.0,
    category: "kid",
  },
  {
    title: "kids' black coat,",
    description: "warmth and style for little ones.",
    image:  "../frontend/product_27.png",
    price: 1785.0,
    category: "kid",
    
  },
  {
    title: "Kid's Light Green Sweatshirt by Adidas,",
    description: "Cozy warmth with a sporty flair.",
    image:  "../frontend/product_28.png",
    price: 299.0,
    category: "kid",
  },
  {
    title: "Boys Orange Colourblocked Hooded Sweatshirt",
    description:"pink pink blooming pink",
    image:  "../frontend/product_30.png",
    price: 285.0,
    category: "kid",
  },
  {
    title: "kids blue hoodie,",
    description: "casual comfort for little ones.",
    image:  "../frontend/product_31.png",
    price: 605.0,
    category: "kid",
  },
  {
    title: "Kids' Black Sweatshirt by H&M,",
    description: "Cozy and stylish for young ones.",
    image:  "../frontend/product_32.png",
    price: 485.0,
    category: "kid",
  },
  {
    title: "grey shirt,",
    description: "versatile and understated.",
    image:  "../frontend/product_34.png",
    price: 585.0,
    category: "kid",
  },
  {
    title: "Stylish Red Kids' Gown by H&M",
    description: "Elegance for young fashionistas.",
    image:  "../frontend/product_36.png",
    price: 1885.0,
    category: "kid"
  },
];


module.exports = {data : sampleCarts };